# Generated by Django 6.0.2 on 2026-02-17 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecorys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablerecouvrement',
            options={'verbose_name': 'Recouvrement', 'verbose_name_plural': 'Recouvrements'},
        ),
    ]
