# Generated by Django 6.0.2 on 2026-02-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecorys', '0002_alter_tablerecouvrement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableniveau',
            name='niveau',
            field=models.CharField(max_length=50, unique=True, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='tableoption',
            name='option',
            field=models.CharField(max_length=50, unique=True, verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='tablepermission',
            name='permission',
            field=models.CharField(max_length=50, unique=True, verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='tablerole',
            name='role',
            field=models.CharField(max_length=50, unique=True, verbose_name='Rôle'),
        ),
    ]
